name: JOCELYN ANNA LERNOUT
favicon: null
layout_spectrum: 0.70573
typography_spectrum: 0.5014315994922072
title: JOCELYN ANNA LERNOUT
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: "\t184.168.221.37"
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b59e7e'
    - '#266a69'
    - '#d0c09c'
    - '#1e3f38'
    - '#806850'
  brandStrength: 0.6875
  lightness: 0.5
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
